#FROM nvidia/cudagl:10.2-devel-ubuntu18.04
FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,video,utility

RUN apt-get update && \
  apt-get -y install --no-install-recommends \
  software-properties-common

# install FFMPEG
RUN add-apt-repository ppa:jonathonf/ffmpeg-4 \
  && apt -y install --no-install-recommends ffmpeg

# install deps (gstreamer)

# gstreamer ppa 1.18
#RUN  add-apt-repository ppa:savoury1/ffmpeg4 && add-apt-repository ppa:savoury1/multimedia

RUN apt-get update && apt-get -y --no-install-recommends install \
    sudo \
    vim \
    wget \
    build-essential \
    autopoint \
    pkg-config \
    python3 \
    python3-pip \
    python3-dev \
    python3-setuptools \
    python3-wheel \
    git \
    libmount-dev \
    ninja-build \
    valgrind yasm nasm bison flex \
    libjpeg-dev qt5-default glib-2.0 libx265-dev libx264-dev \
    libpng-dev libgraphene-1.0-dev libwebrtc-audio-processing-dev \
    libtiff-dev libatlas-base-dev libglib2.0-dev libunwind-dev libdw-dev libgtk-3-dev \
    libtheora-bin libtheora-dev libvorbis-dev alsa-base alsa-tools libcdparanoia-dev libasound2-dev \
    libopus-dev libvisual-0.4-dev libpango1.0-dev libvdpau-dev opencl-dev \
    libx11-dev xorg-dev libgirepository1.0-dev mesa-utils



RUN pip3 install -U meson numpy

# install nvencoder
RUN mkdir /home/gstreamer
COPY *.sh /home/gstreamer/

#download video codec sdk from Nvidia site

COPY ./Video_Codec_SDK_11.0.10/Interface/* /usr/local/cuda/include/
COPY ./Video_Codec_SDK_11.0.10/Lib/linux/stubs/x86_64/* /usr/local/cuda/lib64/stubs/


# clone gst-build
RUN cd /tmp && git clone https://github.com/GStreamer/gst-build.git && \
  cd gst-build && git checkout 1.18.4 && \ 
  meson --prefix=/usr -Dbuildtype=debug build && ninja -C build && \
  ninja -C build install && \
  ldconfig && \
  rm -rf /tmp/gst-build

#ENV LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu/

# OpenCV4
#RUN apt-get -y install cmake
#RUN pip3 install install scikit-build && pip3 install opencv-python opencv-contrib-python
